detectors:
  DuplicateMethodCall:
    max_calls: 2

  IrresponsibleModule:
    enabled: false

  MissingSafeMethod:
    enabled: false

  NestedIterators:
    max_allowed_nesting: 3

  TooManyStatements:
    enabled: true
    exclude:
      - initialize
    max_statements: 10

  UtilityFunction:
    public_methods_only: true

exclude_paths:
  - 'bin'
  - 'config'
  - 'db'
  - 'docker'
  - 'doc'
  - 'frontend'
  - 'log'
  - 'public'
  - 'storage'
  - 'tmp'
  - 'vendor'
