inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'bin/**/*'
    - 'docker/**/*'
    - 'doc/**/*'
    - 'frontend/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'spec/**/*'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'Gemfile.lock'

Bundler/OrderedGems:
  Enabled: true

Rails:
  Enabled: true

Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'
    - 'lib/tasks/dev.rake'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'