inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'bin/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'vendor/**/*'
    - '**/spec_helper.rb'
    - '**/templates/**/*'

Rails:
  Enabled: true

Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'
    - 'lib/tasks/dev.rake'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'
