version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: make rails/run-server
    volumes:
      - .:/usr/src/rails-api-boilerplate
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: "rails-api-boilerplate_db"
    volumes:
      - ./docker/db/mysql_cnf:/etc/mysql/conf.d
      - ./docker/db/mysql_data:/var/lib/mysql:rw
      - ./docker/mysql_init/:/docker-entrypoint-initdb.d/:rw
    environment:
      MYSQL_DATABASE: rails_boilerplate_development
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: officedevfdb01
      MYSQL_PASSWORD: officedevfdb
      TZ: Asia/Tokyo
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "4306:3306"
