json.id task.id
json.name task.name
json.description task.description
json.deadline_at_at task.deadline_at
json.repeats task.repeats
json.is_completed task.is_completed
json.parent_task_id task.parent_task_id
json.assigned_user_id task.assigned_user_id
json.created_user_id task.created_user_id
json.created_at task.created_at
json.updated_at task.updated_at
