# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  static-code-anarisys:
    docker:
      - image: circleci/ruby:2.7.1
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          DB_USERNAME: databaseuser
          DB_PASSWORD: password
      - image: circleci/mysql:5.7.31-ram
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: rails_api_boilerplate_test
          MYSQL_USER: databaseuser
          MYSQL_PASSWORD: password
    working_directory: ~/usr/src/rails-api-boilerplate
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      # Database setup
      - run:
          name: database setup
          command: |
            dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
            make rails/db-setup
      # rails_best_practices
      - run:
          name: run rails_best_practices
          command: make lint/best-practice
      # brakeman
      - run:
          name: run brakeman
          command: make lint/security
      # Rubocop
      - run:
          name: run rubocop
          command: bundle exec rubocop
      # Rspec
      - run:
          name: run rspec
          command: bundle exec rspec

workflows:
  version: 2
  static-code-anarisys:
    jobs:
      - static-code-anarisys
