version: '3'
services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/share/nginx/html/foo
    environment:
      URL: /foo/openapi.yaml
